@startuml Entities
package entities {
    package base {
        class User {}
        class Client {}
        User "1" *-- "0..*" Client: owns/manages
    }
    package layer_one {
        enum ConversationType {
        }
        class Conversation {
            conversation_type: ConversationType
            user_id: string
        }
        class ConversationMessage {
            content: string 
            user_written: boolean
        }
        class ConversationPin {}

        class Project {

        }
    }
    package layer_two {
        class File {}
        class ContentChunk {}

        Project "1" *-- "0..*" File: has many
        File "1" *-- "1..*" ContentChunk: owns
        User "1" -- "0..*" File: owns
        Client "1" -- "0..*" File: owns
    }
    package layer_three {
        class Template {}
        class GaurdrailsEvaluation {}
        class MetricsEvaluation {}

        Conversation "1" -- "0..*" Template: many template data
        User "1" -- "0..*" Template: owns
        ConversationMessage "1" -- "0..*" GaurdrailsEvaluation
        ConversationMessage "1" -- "0..*" MetricsEvaluation
    }

    package layer_four {
        class DocumentGroup {}
        class EnrichedIndex {}
    }
}

User --* Conversation: has many
User --* ConversationPin: has many
User --* Project
Project "1" o-- "0..*" Conversation: (conversation optionally linked to project)
Conversation "1" *-- "0..*" ConversationMessage : owns
Conversation "0..1" -- "1" ConversationPin
@enduml
